scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets: [cadvisor:8080]
      # we can attach a testid here to align with the testid that k6 has
      #labels:
      #  testid: qazwsx
  metric_relabel_configs:
    # here we exclude metrics for containers we are not interested in
    # TODO rather find out how to get cAdvisor to ignore these containers
    # TODO get this to actually work
    - source_labels: [ __param_name ]
      regex: 'grafana|prometheus|cadvisor'  # Regular expression matching the metrics you want to ignore
      action: drop  # Action to perform (in this case, drop the matching metrics)